services:
  # The Node.js Web Server
  - type: web
    name: web-server
    env: node
    plan: free
    rootDir: ./web-server
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: MCP_SERVER_URL
        value: http://mcp-server:9999/mcp

  # The Python MCP Server
  - type: pserv
    name: mcp-server
    env: python
    plan: free
    rootDir: ./flight-findr-mcp
    buildCommand: "pip install -r requirements.txt && playwright install --with-deps"
    startCommand: "python mcp_server.py --transport http"
